// 1 least strict - 14 most strict
// 1 most popular - 13 least popular

const licensesObj = [
  {
    name: "The Unlicense",
    path: "/unlicense",
    src: "",
    image: "",
    description: "",
    strictness: 14,
    popularity: 6,
  },
  {
    name: "Creative Commons Zero v1.0 Universal",
    path: "/cc0",
    src: "",
    image: "",
    description: "",
    strictness: 13,
    popularity: 12,
  },
  {
    name: "MIT License",
    path: "/mit",
    src: "",
    image:
      "https://drive.google.com/uc?export=view&id=1wX5wN_7V_y09lkBYXL5sIhlg9sSOz_F9",
    description: "",
    strictness: 12,
    popularity: 1,
  },
  {
    name: 'BSD 2-Clause "Simplified" License',
    path: "/bsd2",
    src: "",
    image: "",
    description: "",
    strictness: 11,
    popularity: 7,
  },
  {
    name: 'BSD 3-Clause "New" or "Revised" License',
    path: "/bsd3",
    src: "",
    image: "",
    description: "",
    strictness: 10,
    popularity: 5,
  },
  {
    name: "Boost Software License 1.0",
    path: "/bsl1",
    src: "",
    image: "",
    description: "",
    strictness: 9,
    popularity: 13,
  },
  {
    name: "Apache License 2.0",
    path: "/al2",
    src: "",
    image: "",
    description: "",
    strictness: 8,
    popularity: 3,
  },
  {
    name: "Eclipse Public License 2.0",
    path: "/epl2",
    src: "",
    image: "",
    description: "",
    strictness: 7,
    popularity: 11,
  },
  {
    name: "Mozilla Public License 2.0",
    path: "/mpl2",
    src: "",
    image: "",
    description: "",
    strictness: 6,
    popularity: 10,
  },
  {
    name: "GNU General Public License v2.0",
    path: "/gnugpl2",
    src: "",
    image: "",
    description: "",
    strictness: 5,
    popularity: 2,
  },
  {
    name: "GNU Lesser General Public License v2.1",
    path: "/gnulgpl21",
    src: "",
    image: "",
    description: "",
    strictness: 4,
    popularity: 8,
  },
  {
    name: "GNU General Public License v3.0",
    path: "/gnugpl3",
    src: "",
    image: "",
    description: "",
    strictness: 3,
    popularity: 4,
  },
  {
    name: "GNU Affero General Public License v3.0",
    path: "/gnuagpl3",
    src: "",
    image: "",
    description: "",
    strictness: 2,
    popularity: 9,
  },
  {
    name: "None",
    path: "/none",
    src: "",
    image: "",
    description: "",
    strictness: 1,
    popularity: "N/A",
  },
];

export { licensesObj };
